id: T0146
type: Technique

tactic: Defense Evasion

realm: 
  - CI/CD Posture
  - Cloud Security
  - SCM Posture

summary: Misconfigured audit logs settings

description: |
  Misconfigured audit logs are a type of attack where an attacker modifies or disables audit logs to hide their malicious activities. 
  This technique is commonly used in cloud, CI/CD, and SCM environments. 
  In these environments, misconfigured audit logs can allow an attacker to modify or delete logs, making it difficult for security teams to detect and investigate the attack. 
  The attacker can also disable audit logging to evade detection. 

mitigations: 
  - M1440
  - M1441
  - M1550

detections: 
  - D1510
  - D1520

references: 
  - https://blog.marcolancini.it/2019/blog-cross-account-auditing/
  - https://blog.marcolancini.it/continuous-cloud-visibility/

metadata: 
    version: 0.2
    state: draft

  