id: T0147
type: Technique

tactic: Reconnaissance

realm: 
  - CI/CD Posture

summary: Scan public CI/CD configurations for secrets and vulnerable actions

description: |
  This technique involves scanning publicly available CI/CD configurations for potential vulnerabilities, misconfigurations, and secrets.
  An attacker can use this technique to identify misconfigured CI/CD pipelines that may contain secrets or other sensitive information, such as API keys or login credentials. 
  They can also identify vulnerable actions, such as unsecured build agents or outdated software components, that can be exploited to gain access to an organization's infrastructure or data.
  Misconfigured or insecure CI/CD pipelines can introduce significant security risks, including data breaches and system compromise.

mitigations: 
  - M1120
  - M1201
  - M1660
  - M1662
  - M1720

detections: 
  - D1510
  - D1520
  - D1590

references: 
  - https://owasp.org/www-project-top-10-ci-cd-security-risks/
  - https://www.aquasec.com/cloud-native-academy/supply-chain-security/ci-cd-security-threats-tools-and-best-practices/
  - https://cycode.com/github-actions-vulnerabilities/

metadata: 
    version: 0.1
    state: draft

  