id: T0140
type: Technique

tactic: Credential Access

realm: 
  - CI/CD Posture
  - Cloud Security
  - Container Security
  - Infrastructure as code
  - Secrets Hygiene

summary: Harvest tokens from environment variables

description: |
  This type of attack involves searching for environment variables that may contain sensitive information and dumping their values to gain access to the associated resources.
  In cloud and container environments, environment variables are often used to store configuration data, including sensitive information such as passwords, tokens and API keys. 
  Attackers can exploit this by searching through the environment variables of running containers or cloud instances to find any sensitive information that has been inadvertently exposed. 
  Once the sensitive information has been obtained, attackers can use it to access and compromise the associated resources.

mitigations: 
  - M1120
  - M1860
  - M1861

detections: 
  - D1260
  - D1261
  - D1262
  - D1510

references: 
  - https://www.trendmicro.com/en_ie/research/22/h/analyzing-hidden-danger-of-environment-variables-for-keeping-secrets.html
  - https://developer.hashicorp.com/vault/docs/what-is-vault

metadata: 
    version: 0.2
    state: draft

  