id: T0189
type: Technique

tactic: Credential Access

realm:
  - SecretsHygiene

summary: Secrets in configuration files

description: |
          It is a very common mistake for developers to keep secrets in configuration files, these can include user crednetials, private keys, api keys etc...  Those files are usually the first place where adversaries search for such information.  

mitigations: # REQUIRED - <list> -reference to mitigation references
  - 

detections: # REQUIRED - <list> - reference to detection defintitions
  - 

subtechinques: # OPTIONAL <list> - reference to TechIDs
  - 

references: 
  -

metadata: 
    state: draft

  
