# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - content/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: "phips28/gh-action-bump-version@master"
      - run: ls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'npm-package'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

  build:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: python ./helpers/create_pbom_release.py --source content/oscar/ --dest ./npm-package
      - run: | 
          cd ./npm-package
          npm i

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      # - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
